"""add last_alert_month to budgets

Revision ID: 8ae3fd3b6c97
Revises: 8f1634d3a77f
Create Date: 2026-08-02 04:45:01.377862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae3fd3b6c97'
down_revision: Union[str, Sequence[str], None] = '8f1634d3a77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('last_alert_month', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'last_alert_month')
    # ### end Alembic commands ###
