import { useEffect, useState } from 'react'
import { Sparkles, BrainCircuit, ListChecks } from 'lucide-react'
import { api } from '@/lib/api'
import type { InsightResponse } from '@/types'
import { PageHeader, Spinner, EmptyState } from '@/components/ui/Misc'
import { Card } from '@/components/ui/Card'

export default function Insights() {
  const [data, setData] = useState<InsightResponse | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    api.insights.get().then((res) => {
      setData(res)
      setLoading(false)
    })
  }, [])

  return (
    <div>
      <PageHeader
        eyebrow="AI"
        title="Insights"
        description="Patterns and nudges pulled from your spending."
      />

      {loading ? (
        <div className="flex h-40 items-center justify-center"><Spinner className="h-5 w-5 text-forest-500" /></div>
      ) : !data || data.insights.length === 0 ? (
        <Card>
          <EmptyState
            icon={<Sparkles size={28} />}
            title="No insights yet"
            description="Log a few more transactions and check back — insights improve with more data."
          />
        </Card>
      ) : (
        <>
          <div className="mb-4 flex items-center gap-2 text-xs font-medium text-mist">
            {data.generated_by === 'llm' ? <BrainCircuit size={14} /> : <ListChecks size={14} />}
            Generated by {data.generated_by === 'llm' ? 'AI model' : 'rule-based analysis'}
          </div>
          <div className="space-y-3">
            {data.insights.map((text, i) => (
              <Card key={i} className="flex items-start gap-3 border-brass-300/60 bg-brass-100/30 p-4">
                <Sparkles size={18} className="mt-0.5 shrink-0 text-brass-600" />
                <p className="text-sm text-ink-soft">{text}</p>
              </Card>
            ))}
          </div>
        </>
      )}
    </div>
  )
}
